# -*- coding: utf-8 -*-
"""Untitled131.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fxSsVQBjghCO-jhiPN7P4UAq4gIQtsi
"""

pip install -U googlemaps



pip install googlemaps gmplot

pip install haversine

import googlemaps
from haversine import haversine

def calculate_square_feet(api_key, coordinates):
    gmaps = googlemaps.Client(key=api_key)

    # Convert coordinates to distances
    distances = [haversine(coord1, coord2) for coord1, coord2 in zip(coordinates[:-1], coordinates[1:])]

    # Convert distances to meters (1 degree of latitude/longitude is approximately 111 kilometers)
    distances_meters = [distance * 1000 for distance in distances]

    # Calculate area in square meters using the shoelace formula
    area_meters = 0.5 * sum(x * y for x, y in zip(distances_meters, distances_meters[1:] + distances_meters[:1]))
    area_feet = area_meters * 10.764

    return area_feet
api_key = 'AIzaSyCjM4i7qZtNg7bRWGmBJJNtlfoBcLtewXs'
polygon_coordinates = [
    (13.159500540747207, 78.68170225004698),
    (13.159485350721786, 78.6815723395217),
    (13.159347929654805, 78.68155579469607),
    (13.159283408969408, 78.68186860480104),
    (13.159436153226764, 78.68190450240255)
]
square_feet = calculate_square_feet(api_key, polygon_coordinates)

print(f"Approximate Area in Square Feet: {square_feet} sq. ft")